AWSTemplateFormatVersion: "2010-09-09"
Description: Template para criar uma instância EC2 básica.

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Tipo de instância EC2 (por exemplo, t2.micro, t2.small).
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Deve ser um tipo de instância EC2 válido.

  AMIId:
    Type: String
    Default: ami-0c02fb55956c7d316 # AMI do Amazon Linux 2 para us-east-1
    Description: ID da imagem AMI para inicializar a instância.

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIId
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acesso SSH e HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: ID da instância EC2 criada.
    Value: !Ref MyEC2Instance

  PublicIP:
    Description: Endereço IP público da instância EC2.
    Value: !GetAtt MyEC2Instance.PublicIp
